language: android
android:
  components:
    - build-tools-23.0.1
    - android-23
    - add-on
    - extra
    - platform-tools
    - tools
    - extra-google-google_play_services
    - extra-google-m2repository
    - extra-android-m2repository
    - addon-google_apis-google-19
    - sys-img-armeabi-v7a-android-23

deploy:
  provider: releases
  api_key: $GITHUB_KEY
  file: app-mvp-dagger/build/outputs/apk/app-mvp-dagger-release.apk
  skip_cleanup: true
  on:
    tags: true

notifications:
  email:
    recipients:
    - bataritosz@gmail.com
    on_failure: always